server:
  port: 8003

spring:
  application:
    name: demo-consumer
  zipkin:
    base-url: http://localhost:9003
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    instance-id: demo-consumer:8003
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

order-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
